.PHONY: setup tests lint typecheck run-pre-commit audit audit-realistic generate-realistic-dataset third-party-notices generate-full-dataset

setup:
	uv sync

tests:
	uv run pytest .

lint:
	uv run ruff check .

typecheck:
	# notebooks/ has no .py files left (session 13 removed the last one,
	# fhir_match_data_source.py) - just evaluation/ to check.
	uv run mypy evaluation

run-pre-commit:
	uv run pre-commit run --all-files

generate-full-dataset: ## Generate test cases from all 9 ONC shards (~1M records), one shard at a time - see evaluation/SYNTHETIC_DATA_SETUP.md's "Memory & scale" section
	PYTHONPATH=. uv run python evaluation/export_full_onc_dataset.py

third-party-notices: ## Regenerate THIRD-PARTY-NOTICES.md from the current dependency tree
	@echo "# Third-Party Notices" > THIRD-PARTY-NOTICES.md
	@echo "" >> THIRD-PARTY-NOTICES.md
	@echo "This file is generated by \`make third-party-notices\` — do not hand-edit." >> THIRD-PARTY-NOTICES.md
	@echo "" >> THIRD-PARTY-NOTICES.md
	@echo "## Python dependencies" >> THIRD-PARTY-NOTICES.md
	@echo "" >> THIRD-PARTY-NOTICES.md
	uv run pip-licenses --format=markdown --with-urls >> THIRD-PARTY-NOTICES.md

audit: ## Print the dataset audit and evaluate the release gate (see evaluation/release_thresholds.json)
	PYTHONPATH=. uv run python evaluation/release_gate.py

generate-realistic-dataset: ## Generate the age/household-realistic release candidate (realistic_*.jsonl) from all 9 ONC shards, one at a time
	PYTHONPATH=. uv run python evaluation/export_realistic_dataset.py

audit-realistic: ## Evaluate release_thresholds_realistic.json against the generated realistic_*.jsonl files
	PYTHONPATH=. uv run python evaluation/release_gate.py realistic
