.PHONY: setup tests lint typecheck run-pre-commit third-party-notices

setup:
	uv sync

tests:
	uv run pytest .

lint:
	uv run ruff check .

typecheck:
	# notebooks/ has no .py files left (session 13 removed the last one,
	# fhir_match_data_source.py) - just evaluation/ to check.
	uv run mypy evaluation

run-pre-commit:
	uv run pre-commit run --all-files

third-party-notices: ## Regenerate THIRD-PARTY-NOTICES.md from the current dependency tree
	@echo "# Third-Party Notices" > THIRD-PARTY-NOTICES.md
	@echo "" >> THIRD-PARTY-NOTICES.md
	@echo "This file is generated by \`make third-party-notices\` — do not hand-edit." >> THIRD-PARTY-NOTICES.md
	@echo "" >> THIRD-PARTY-NOTICES.md
	@echo "## Python dependencies" >> THIRD-PARTY-NOTICES.md
	@echo "" >> THIRD-PARTY-NOTICES.md
	uv run pip-licenses --format=markdown --with-urls >> THIRD-PARTY-NOTICES.md
